[[manager.prepend_keymap]]
on   = [ "l" ]
run  = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on = [ "H" ]
run = "hidden toggle"
desc = "Toggles hidden files"


[[manager.prepend_keymap]]
on = [ "g", "p" ]
run = "cd ~/Projects/FCI"
desc = "Cd to ~/Projects/FCI"

[[manager.prepend_keymap]]
on = ["T"]
run = "shell 'tmux new-window -c \"$PWD\"' --confirm"
desc = "New tmux window here" 

[[manager.prepend_keymap]]
on = [" ", "s"]
run = "sort modified --dir-first=no --reverse"
desc = "Sort modified" 

[[manager.prepend_keymap]]
on = [" ", "n"]
run = "sort alphabetical --dir-first"
desc = "Return to default sort" 
