export-configs:
	mv -r ~/.config/nvim ~/.config/nvim.bak 
	mv -r ~/.tmux ~/.tmux.bak 
	mv ~/.tmux.conf ~/.tmux.conf.bak 
	mv ~/.zshrc ~/.zshrc.bak
	cp -r .* ~

import-configs:
	cp -r ~/.config/nvim .config 
	cp ~/.zshrc .
	cp ~/.tmux.conf .
	cp -r ~/.tmux .

